### ISSUE TITLE
No way to close PipeWrite and make PipeRead return EOF

### ISSUE THREAD

**Issue by bradhe** [yskszk63/tokio-pipe#30]
Maybe I'm just missing something in the API; however, after some searching around and [an unsuccessful Discord](https://discord.com/channels/273534239310479360/1088131114687811766/1088131114687811766) posts I thought I'd open an issue to get some thoughts.

I'm working on, basically, a process that downloads a `.tar.gz` file from the internet and needs to pipes the content into a future that untars it in place. My program uses tokio as the async runtime and I'm using tokio_pipe to manage the pipes.

When there's a problem on the download side, I'm not sure how to signal to the read side that it should give up. Wondering if anyone has suggestions? Maybe just a timeout?

```rust
use async_compression::tokio::bufread::GzipDecoder;
use async_tar::Archive;
use std::path::Path;
use tokio::io::{AsyncRead, AsyncWriteExt, BufReader};
use tokio_util::compat::TokioAsyncReadCompatExt;

async fn untar_stream<R: AsyncRead + Unpin>(r: R, dst: &Path) {
    let r = BufReader::new(r);
    let r = GzipDecoder::new(r);
    Archive::new(r.compat()).unpack(&dst).await.unwrap();
}

async fn write_content<W: AsyncWriteExt + Unpin>(_out: &mut W) {
    // Nothing gets written here due to a failure of some kind.
}

async fn untar_path(_src: &Path, dst: &Path) {
    let (read, mut write) = tokio_pipe::pipe().expect("pipe creation failed");
    let writer = write_content(&mut write);
    let reader = untar_stream(read, dst);
    tokio::join!(writer, reader);
}

#[tokio::main]
async fn main() {
    untar_path(&Path::new("./data/files.tar.gz"), &Path::new("./dest")).await;
}
```

Maybe I'm using this wrong entirely, or perhaps there's something in the API that I missed.

**Comment by NobodyXu** [comment]
`PipeWrite` is closed on drop, so you need to take `write` by value in `write_content`:

```rust
async fn write_content<W: AsyncWrite + Unpin>(_out: W) {
    // Nothing gets written here due to a failure of some kind.
}

async fn untar_path(_src: &Path, dst: &Path) {
    let (read, write) = tokio_pipe::pipe().expect("pipe creation failed");
    let writer = write_content(write);
    let reader = untar_stream(read, dst);
    tokio::join!(writer, reader);
}
```

Also, a few suggestion to your code:

 - I recommend you to use `tokio::sync::mpsc` or other channel and send `bytes::Bytes` over it instead of `tokio_pipe`,
   since read from or write to pipes require a syscall and copying data between userspace and kernelspace.
   Using `mpsc`, the data does not go through the syscall and does not need that copy.
   `bytes::Bytes` can be used to achieve zero copy if you preallocate `Bytes` to be large enough so that
   `untar_stream` would consume the data before next write in `write_content`.
 - I recommend replacing `tokio::join!(writer, reader)` with:
   ```rust
   tokio::join!(
       async move { tokio::spawn(writer).await.unwrap() },
       async move { tokio::spawn(reader).await.unwrap() },
   );
   ```
   spawning a task would enable it to run on a separate thread in parallel to each other
   and would improve polling efficiency since top-level polling is always more efficient.

**Comment by bradhe** [comment]
Wow, these are great! Thanks a lot for your help on this. I'll try these out--looks like indeed I just didn't understand the API (or some of nuances of the tokio runtime).
